export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESSS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";

export const GET_USERS_POSTS = "GET_USERS_POSTS";
export const GET_USERS_POSTS_SUCCESS = "GET_USERS_POSTS_SUCCESSS";
export const GET_USERS_POSTS_FAIL = "GET_USERS_POSTS_FAIL";